### ISSUE TITLE
Alinhamento código de conduta

### ISSUE THREAD

**Issue by Amandasv** [AfroPython/afropython-site#21]
![print_codigodeconduta](https://user-images.githubusercontent.com/11274228/30890729-fbeb83f4-a304-11e7-8f3f-5e7734ced6fe.png)

Quando esta em telas menores, essa parte de Reportanto Assédio, esta centralizada, e todo o restante segue o alinhamento para a esquerda. Acho que precisamos deixar iguais...

**Comment by cynthiapereira** [comment]
Posso ajudar com isso!
