### ISSUE TITLE
Pequeno bug no rodapé

### ISSUE THREAD

**Issue by Amandasv** [AfroPython/afropython-site#22]
![bugrodape](https://user-images.githubusercontent.com/11274228/30891377-62ea6508-a309-11e7-8b79-3731cbbfd440.png)
Tem um pequeno espaçamento entre o fim do rodapé e fim da página.

**Comment by rafaelweiblen** [comment]
talvez vocês estejam trabalhando nessa parte ainda, mas o link de contato leva para a própria página. Deveria ir para um email? ou form de contato?

**Comment by rafaelweiblen** [comment]
Esquece agora vi o que esta em doing. desculpa :(

**Comment by Amandasv** [comment]
heheh, mas valeu @rafaelweiblen :D
