### ISSUE TITLE
Tradução do nosso Readme para EN

### ISSUE THREAD

**Issue by Amandasv** [AfroPython/afropython-site#44]
Nosso [README](https://github.com/AfroPython/afropython-site/blob/master/README.md) está escrito somente em Português, seria interessante ter logo abaixo, a versão em inglês também :)

**Comment by Nosferatul** [comment]
can I try it? 😄

**Comment by FernandaOchoa** [comment]
Can I try to help to translate?? or maybe translate to spanish!

**Comment by lipemorais** [comment]
This project has not at this moment as a main goal to be translated for different languages. So we will close this issue. May you could help us with the [our tutorial](github.com/afropython/tutorial).
