### ISSUE TITLE
Tradução do Código de Conduta para EN

### ISSUE THREAD

**Issue by Amandasv** [AfroPython/afropython-site#45]
Nosso [Código de Conduta](https://github.com/AfroPython/afropython-site/wiki/C%C3%B3digo-de-Conduta) está escrito somente em Português, seria interessante termoas a versão em inglês também :)

**Comment by cynthiapereira** [comment]
I would like to take this, however GitHub does not support PR for the Wiki, so what we can do?

**Comment by Amandasv** [comment]
Hello @cynthiapereira, how are you?
You can send us a file (preference in markdown) and we update to the Wiki, can it be for you?

<3
