### ISSUE TITLE
Link do Waffle quebrado

### ISSUE THREAD

**Issue by neriGabriel** [AfroPython/afropython-site#76]
Opa, então eu estava dando uma lida no projeto e achei legal queria contribuir porém quando fui ver algumas tarefas a serem feitas pelo link disponibilizado [(waffle)](https://waffle.io/AfroPython/afropython-site) e o mesmo está "quebrado".

**Comment by pedrro** [comment]
Olá Gabriel, tudo bom? Nem esquenta com isso, não estamos mais usando o waffle!

No momento estamos passando por reformulações na estrutura do site então não temos estórias priorizadas, mas se você quiser contribuir pode olhar a #68 ou #74
