### ISSUE TITLE
Adicionar Microsoft como patrocinadora

### ISSUE THREAD

**Issue by pedrro** [AfroPython/afropython-site#92]
Commit com referência do que foi utilizado no ultimo evento:
https://github.com/AfroPython/afropython-site/commit/410ac4ca2219bfb62fcf1dbf4cabb88fdc383b8e#diff-528c3923d718a8860f5d8c05c3931c55

Não temos uma imagem da Microsoft como referência, aceitamos sugestões.
A imagem deve ser colocada junto com as outras patrocinadoras, dentro da pasta:
src/images/sponsors

**Comment by camilla-m** [comment]
Vou pegar esse tb
